name: Append Pull Request Link

on:
  pull_request:
    types:
      - closed
  workflow_call:
  push:
    branches:
    - aman
jobs:
  append-pull-request-link:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged
        run: |
          if [ "${{ github.event.pull_request.merged }}" != "true" ]; then
            echo "Pull request not merged, skipping..."
            exit 0
          fi

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set committer identity
        run: |
          git config --global user.email "yugaa22@gmail.com"
          git config --global user.name "yugaa22"

      - name: Append pull request link to commit message
        run: |
          # Retrieve the pull request number and repository name
          PULL_NUMBER="${{ github.event.pull_request.number }}"
          REPO_NAME="${{ github.repository }}"
          
          git pull

          # Get the latest commit SHA of the merged pull request
          LATEST_COMMIT_SHA=$(git log -1 --pretty=format:%H)

          # Construct the pull request link
          PULL_REQUEST_LINK="https://github.com/$REPO_NAME/pull/$PULL_NUMBER"

          # Append the pull request link to the commit message
          COMMIT_MESSAGE="$(git log -1 --pretty=format:%B)"
          NEW_COMMIT_MESSAGE="$COMMIT_MESSAGE (Pull Request: $PULL_REQUEST_LINK)"
          echo "$NEW_COMMIT_MESSAGE" > new_commit_message.txt
          git commit --amend -F new_commit_message.txt
          rm new_commit_message.txt
          git add .
          git status
          git branch
          git commit -m "Developper_commits"
          git push https://yugaa22:${{ secrets.GIT_TOKEN }}@github.com/opsmx/kork-oes.git origin --force
